name: litpic
description: Mobile app for requested customed 3D printing lithophanes.
author: Trey Hope <tr3designs.prints@gmail.com>

version: 1.1.1+111

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  algolia: ^1.0.1
  bottom_navy_bar: ^6.0.0
  cloud_firestore: ^1.0.5
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.0.1
  equatable: ^2.0.0
  expandable: ^5.0.1
  # firebase_analytics: ^8.0.0
  firebase_auth: ^1.1.0
  firebase_auth_web: ^1.1.0
  firebase_core: ^1.0.3
  # firebase_crashlytics: ^0.2.4
  firebase_messaging: ^9.1.1
  firebase_messaging_web: ^1.0.6
  firebase_storage: ^8.0.3
  flutter_custom_clippers: ^1.1.2 
  flutter_phoenix: ^1.0.0
  flutter_speed_dial: ^3.0.5
  flutter_statusbarcolor: ^0.2.3
  flutter_bloc: ^7.0.0
  getwidget: ^1.1.0
  get_it: ^6.1.1
  http: ^0.13.1
  image_cropper: ^1.3.1
  image_downloader: ^0.30.0
  image_picker: ^0.7.4
  intl: ^0.17.0
  material_design_icons_flutter: ^4.0.5755
  money2: ^2.0.2
  package_info: ^2.0.0
  pagination: ^0.1.0
  pie_chart: ^5.0.0
  reorderables: ^0.4.1
  rxdart: ^0.26.0
  settings_ui: ^1.0.0
  share: ^2.0.1
  shared_preferences: ^2.0.5
  timeago: ^3.0.2
  tutorial_coach_mark: ^1.0.0
  dependencies:
  universal_io: ^2.0.4
  url_launcher: ^6.0.3
  uuid: ^3.0.4
  youtube_parser: ^1.1.0
  youtube_player_flutter: ^8.0.0
  pdf: ^3.2.0
  printing: ^5.1.0
  path_provider: ^2.0.1
  # native_pdf_view: ^4.0.1
  open_file: ^3.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/fitness_app/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          style: italic