name: litpic
description: Mobile app for requested customed 3D printing lithophanes.
author: Trey Hope <tr3designs.prints@gmail.com>

version: 1.0.13+13

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  algolia: ^0.1.6+1
  # cached_network_image: ^1.1.3
  cloud_firestore: ^0.12.9+1
  curved_navigation_bar: ^0.3.1
  dash_chat: ^1.0.8
  device_info: ^0.4.0+2
  firebase_auth: ^0.14.0+3
  firebase_core: ^0.4.0+9
  firebase_messaging: ^5.1.6
  firebase_storage: ^3.0.6
  flutter_custom_clippers: ^1.0.4
  flutter_money_formatter: ^0.8.3
  flutter_statusbarcolor: ^0.2.3
  get_it: ^3.0.1
  http: ^0.12.0+1 
  package_info: ^0.4.0+6
  provider: ^3.1.0+1
  image_cropper: ^1.1.0
  image_downloader: ^0.19.1
  image_picker: ^0.6.1+3
  intl: ^0.15.7
  material_design_icons_flutter: ^3.2.4096
  simple_animations: ^1.3.3
  share: ^0.6.0+1
  shared_preferences: ^0.5.4+3
  timeago: ^2.0.10
  url_launcher: ^5.0.1
  uuid: ^2.0.1
  youtube_player: ^3.5.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/fitness_app/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          style: italic