name: litpic
description: Mobile app for requested customed 3D printing lithophanes.
author: Trey Hope <tr3designs.prints@gmail.com>

version: 1.1.2+112

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  algolia: ^1.0.1
  app_tracking_transparency: ^2.0.1
  bottom_navy_bar: ^6.0.0
  cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.3
  currency_text_input_formatter: ^2.1.0
  equatable: ^2.0.3
  expandable: ^5.0.1
  # firebase_analytics: ^8.0.0
  firebase_auth: ^3.0.1
  firebase_auth_web: ^3.0.0
  firebase_core: ^1.4.0
  # firebase_crashlytics: ^0.2.4
  firebase_messaging: ^10.0.5
  firebase_messaging_web: ^2.0.3
  firebase_storage: ^10.0.1
  flutter_custom_clippers: ^2.0.0 
  flutter_phoenix: ^1.0.0
  flutter_speed_dial: ^4.2.0
  # flutter_statusbarcolor: ^0.2.3
  flutter_bloc: ^7.1.0
  getwidget: ^2.0.3
  get_it: ^7.2.0
  http: ^0.13.3
  image_cropper: ^1.4.1
  image_downloader: ^0.30.0
  image_picker: ^0.8.2
  intl: ^0.17.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  money2: ^2.2.1
  package_info: ^2.0.2
  # pagination: ^0.1.0
  pie_chart: ^5.0.0 
  reorderables: ^0.4.1
  rxdart: ^0.27.1
  settings_ui: ^1.0.0
  share: ^2.0.4
  shared_preferences: ^2.0.6
  timeago: ^3.1.0
  tutorial_coach_mark: ^1.0.3
  universal_io: ^2.0.4
  url_launcher: ^6.0.9
  uuid: ^3.0.4
  youtube_parser: ^2.0.0
  youtube_player_flutter: ^8.0.0
  pdf: ^3.4.2
  printing: ^5.4.3
  path_provider: ^2.0.2
  # native_pdf_view: ^4.0.1
  open_file: ^3.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/fitness_app/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          style: italic